# true/false run without clicks
DryRun = true

# scale all time values by
TimeScale = 1

# mouse x offset, use incase of multi-monitor set up and game is not on 1st monitor
# offset by the width of the monitors
WindowXOffset = 0

NumberOfBlackPotions = 12
NumberOfAbsorbPotions = 12

PrayerOrb = { x = 0.867708, y = 0.137037 }
